version: '3'
services:
  app:
    ports:
      - "8000:80"
    build: ./docker/app
    container_name: lt-app
    volumes:
      - ./:/var/www/html
    healthcheck:
      test: ["CMD", "curl -f http://localhost/"]
      interval: "1s"
      timeout: "1s"
      retries: 0
    environment:
      TZ: 'Asia/Tokyo'
  db:
    image: mysql:5.7
    container_name: lt-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_training
      MYSQL_USER: lt_user
      MYSQL_PASSWORD: lt_user
      MYSQL_TCP_PORT: 3307
      TZ: 'Asia/Tokyo'
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    expose:
      - 3307
